#ifndef ih_infi_seq_request_get_since_timestamp_h
#define ih_infi_seq_request_get_since_timestamp_h

#include "ih/core/bool.h"
#include "ih/core/message.h"

struct ih_infi_seq_request_get_since_timestamp_t;
typedef struct ih_infi_seq_request_get_since_timestamp_t
ih_infi_seq_request_get_since_timestamp_t;

ih_core_bool_t ih_infi_seq_request_get_since_timestamp_add_to_message
(void *request_get_since_timestamp_object, ih_core_message_t *message);

ih_infi_seq_request_get_since_timestamp_t *
ih_infi_seq_request_get_since_timestamp_create
(char *subject, unsigned long timestamp);

ih_infi_seq_request_get_since_timestamp_t *
ih_infi_seq_request_get_since_timestamp_create_from_message
(ih_core_message_t *message);

void ih_infi_seq_request_get_since_timestamp_destroy
(ih_infi_seq_request_get_since_timestamp_t *request_get_since_timestamp);

char *ih_infi_seq_request_get_since_timestamp_get_subject
(ih_infi_seq_request_get_since_timestamp_t *request_get_since_timestamp);

unsigned long ih_infi_seq_request_get_since_timestamp_get_timestamp
(ih_infi_seq_request_get_since_timestamp_t *request_get_since_timestamp);

#endif
